name: smartsheet
description: Client for https://smartsheet-platform.github.io
dependencies:
  # http: '>=0.11.3+13 <0.12.0'
  http: '0.11.3+9'
  shelf: '>=0.6.7+2 <0.7.0'
  shelf_route: '>=0.14.3 <0.15.0'
dev_dependencies:
  test: '>=0.12.20+10 <0.13.0'
  shelf_cors: '>=0.2.1 <0.3.0'
